mqtt:
  host: homeassistant.local
  user: mqtt-devices
  password: mqtt-password
  status_payload_running: available
  status_payload_stopped: unavailable
  status_payload_dead: unavailable
  client_id: mqtt-io-pool
  topic_prefix: mqtt-io-pool
  ha_discovery:
    enabled: true
    name: "Raspberry Pi Zero-Pool MQTT-IO"

 # GPIO
gpio_modules:
  # Use the Raspberry Pi built-in GPIO
  - name: rpi
    module: raspberrypi

digital_outputs:
  - name: pool_acid_pump
    module: rpi
    pin: 19
    inverted: true
    timed_set_ms: 10000
    initial: "high"
    publish_initial: true
    retain: true
    ha_discovery:
      name: Pool Acid Pump
