mqtt:
  host: homeassistant.local
  user: mqtt-devices
  password: mqtt-password
  status_payload_running: available
  status_payload_stopped: unavailable
  status_payload_dead: unavailable
  ha_discovery:
    enabled: true
    name: "Raspberry Pi Zero-Pool MQTT-IO"

 # GPIO
gpio_modules:
  # Use the Raspberry Pi built-in GPIO
  - name: rpi
    module: raspberrypi

digital_outputs:
  - name: pool_acid_pump
    module: rpi
    pin: 19
    inverted: true
    timed_set_ms: 10000
    initial: "high"
    publish_initial: true
    ha_discovery:
      name: Pool Acid Pump

sensor_modules:
  - name: adc
    module: ads1x15
    type: ADS1115
    chip_addr: 0x48
    pin: 0

sensor_inputs:
  - name: pool_filter_pressure
    module: adc
    interval: 15
    ha_discovery:
      name: Pool Filter Pressure
