mqtt:
  host: homeassistant.local
  user: mqtt-devices
  password: mqtt-password
  status_payload_running: available
  status_payload_stopped: unavailable
  status_payload_dead: unavailable
  ha_discovery:
    enabled: true
    name: "Raspberry Pi Zero-Pool MQTT-IO"

 # GPIO
gpio_modules:
  # Use the Raspberry Pi built-in GPIO
  - name: rpi
    module: raspberrypi

digital_outputs:
  # Pin 1 is an output connected to a light
  - name: pool_acid_pump
    module: rpi
    pin: 19
    inverted: true
    timed_set_ms: 10000
    initial: "high"
    publish_initial: true
    ha_discovery:
      name: Pool Acid Pump

# Sensors
# sensor_modules:
#   # An LM75 sensor attached to the I2C bus
#   - name: lm75_sensor
#     module: lm75
#     i2c_bus_num: 1
#     chip_addr: 0x48

# sensor_inputs:
#   # The configuration of the specific sensor value to use (LM75 only has temperature)
#   - name: porch_temperature
#     module: lm75_sensor

# # Streams
# stream_modules:
#   # A serial port to communicate with the house alarm system
#   - name: alarm_system
#     module: serial
#     device: /dev/ttyUSB0
#     baud: 9600